version: '3.8'
services:
  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    image: grafana/grafana:latest
    ports:
      - "3009:3000"
    restart: always
    volumes:
      - grafana-storage:/var/lib/grafana
volumes:
  grafana-storage: