global:
  scrape_interval:     15s # Default scrape interval
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus' # Job to scrape Prometheus metrics
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  # - job_name: 'spring-actuator-1'
  #   metrics_path: '/actuator/prometheus'
  #   scrape_interval: 5s
  #   static_configs:
  #     - targets: ['host.docker.internal:3000']
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']
  - job_name: 'app-producer'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:3000']
        labels:
          application: 'App Producer'
  - job_name: 'app-consumer'
    metrics_path: '/actuator/health'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:3001']
        labels:
          application: 'App Consumer'
  - job_name: 'kafka'
    scrape_interval: 10s
    static_configs:
      - targets: ['kafka-exporter:9308']
    metrics_path: /metrics
rule_files:
  - 'alert-rules.yaml'
alerting:
  alertmanagers:
    - scheme: http
    - static_configs:
        - targets: ['alertmanager:9093']